const ajot = [
    { id: 1, nimi: 'Ajo 1', paivamaara: '12.01.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Helsinki', kollienMaara: 10, lisaTiedot: 'Tarkista öljytaso', status: 'Ei aloitettu' },
    { id: 2, nimi: 'Ajo 2', paivamaara: '15.01.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Tampere', kollienMaara: 15, lisaTiedot: 'Toimitus klo 10', status: 'Aloitettu' },
    { id: 3, nimi: 'Ajo 3', paivamaara: '18.01.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Turku', kollienMaara: 20, lisaTiedot: 'Kiireellinen kuljetus', status: 'Suoritettu' },
    { id: 4, nimi: 'Ajo 4', paivamaara: '21.01.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Oulu', kollienMaara: 5, lisaTiedot: 'Tarkista renkaat', status: 'Ei aloitettu' },
    { id: 5, nimi: 'Ajo 5', paivamaara: '25.01.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Espoo', kollienMaara: 8, lisaTiedot: 'Sisältää vaarallista aineistoa', status: 'Aloitettu' },
    { id: 6, nimi: 'Ajo 6', paivamaara: '28.01.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Vantaa', kollienMaara: 12, lisaTiedot: 'Polttoaine on vähissä', status: 'Suoritettu' },
    { id: 7, nimi: 'Ajo 7', paivamaara: '01.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Jyväskylä', kollienMaara: 18, lisaTiedot: 'Pitkä matka', status: 'Ei aloitettu' },
    { id: 8, nimi: 'Ajo 8', paivamaara: '04.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Lahti', kollienMaara: 9, lisaTiedot: 'Aikataulu tiukka', status: 'Aloitettu' },
    { id: 9, nimi: 'Ajo 9', paivamaara: '07.02.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Kuopio', kollienMaara: 14, lisaTiedot: 'Tarkista ilmanpaineet', status: 'Suoritettu' },
    { id: 10, nimi: 'Ajo 10', paivamaara: '10.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kouvola', kollienMaara: 7, lisaTiedot: 'Erikoistoimitus', status: 'Ei aloitettu' },
    { id: 11, nimi: 'Ajo 11', paivamaara: '13.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Pori', kollienMaara: 22, lisaTiedot: 'Sisältää ruokatarvikkeita', status: 'Aloitettu' },
    { id: 12, nimi: 'Ajo 12', paivamaara: '16.02.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Lappeenranta', kollienMaara: 6, lisaTiedot: 'Tarkista jarrut', status: 'Suoritettu' },
    { id: 13, nimi: 'Ajo 13', paivamaara: '19.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Vaasa', kollienMaara: 11, lisaTiedot: 'Toimitus klo 14', status: 'Ei aloitettu' },
    { id: 14, nimi: 'Ajo 14', paivamaara: '22.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kotka', kollienMaara: 3, lisaTiedot: 'Tarkkaile sääolosuhteita', status: 'Aloitettu' },
    { id: 15, nimi: 'Ajo 15', paivamaara: '25.02.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Joensuu', kollienMaara: 17, lisaTiedot: 'Polttoaineen lisäys', status: 'Suoritettu' },
    { id: 16, nimi: 'Ajo 16', paivamaara: '28.02.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Hämeenlinna', kollienMaara: 24, lisaTiedot: 'Suuri toimitus', status: 'Ei aloitettu' },
    { id: 17, nimi: 'Ajo 17', paivamaara: '03.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Seinäjoki', kollienMaara: 13, lisaTiedot: 'Erikoiskuljetus', status: 'Aloitettu' },
    { id: 18, nimi: 'Ajo 18', paivamaara: '06.03.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Rovaniemi', kollienMaara: 2, lisaTiedot: 'Lisäys klo 9', status: 'Suoritettu' },
    { id: 19, nimi: 'Ajo 19', paivamaara: '09.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Mikkeli', kollienMaara: 25, lisaTiedot: 'Sisältää lääkkeitä', status: 'Ei aloitettu' },
    { id: 20, nimi: 'Ajo 20', paivamaara: '12.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kokkola', kollienMaara: 16, lisaTiedot: 'Pitkä matka', status: 'Aloitettu' },
    { id: 21, nimi: 'Ajo 21', paivamaara: '15.03.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Hyvinkää', kollienMaara: 4, lisaTiedot: 'Öljyn lisäys', status: 'Suoritettu' },
    { id: 22, nimi: 'Ajo 22', paivamaara: '18.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Lohja', kollienMaara: 21, lisaTiedot: 'Kuljetus klo 12', status: 'Ei aloitettu' },
    { id: 23, nimi: 'Ajo 23', paivamaara: '21.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kerava', kollienMaara: 1, lisaTiedot: 'Pieni toimitus', status: 'Aloitettu' },
    { id: 24, nimi: 'Ajo 24', paivamaara: '24.03.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Imatra', kollienMaara: 19, lisaTiedot: 'Polttoaine vähissä', status: 'Suoritettu' },
    { id: 25, nimi: 'Ajo 25', paivamaara: '27.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Nokia', kollienMaara: 23, lisaTiedot: 'Kuljetus klo 8', status: 'Ei aloitettu' },
    { id: 26, nimi: 'Ajo 26', paivamaara: '30.03.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Savonlinna', kollienMaara: 14, lisaTiedot: 'Sisältää ruokatarvikkeita', status: 'Aloitettu' },
    { id: 27, nimi: 'Ajo 27', paivamaara: '02.04.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Kemi', kollienMaara: 10, lisaTiedot: 'Öljytaso tarkistettava', status: 'Suoritettu' },
    { id: 28, nimi: 'Ajo 28', paivamaara: '05.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Riihimäki', kollienMaara: 6, lisaTiedot: 'Kuljetus iltapäivällä', status: 'Ei aloitettu' },
    { id: 29, nimi: 'Ajo 29', paivamaara: '08.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Rauma', kollienMaara: 18, lisaTiedot: 'Toimitus klo 11', status: 'Aloitettu' },
    { id: 30, nimi: 'Ajo 30', paivamaara: '11.04.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Kangasala', kollienMaara: 9, lisaTiedot: 'Polttoaine lisäys', status: 'Suoritettu' },
    { id: 31, nimi: 'Ajo 31', paivamaara: '14.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Raahe', kollienMaara: 12, lisaTiedot: 'Kiireellinen', status: 'Ei aloitettu' },
    { id: 32, nimi: 'Ajo 32', paivamaara: '17.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Raisio', kollienMaara: 5, lisaTiedot: 'Sisältää vaarallista aineistoa', status: 'Aloitettu' },
    { id: 33, nimi: 'Ajo 33', paivamaara: '20.04.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Ylöjärvi', kollienMaara: 7, lisaTiedot: 'Tarkista ilmanpaineet', status: 'Suoritettu' },
    { id: 34, nimi: 'Ajo 34', paivamaara: '23.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Mäntsälä', kollienMaara: 25, lisaTiedot: 'Erikoiskuljetus', status: 'Ei aloitettu' },
    { id: 35, nimi: 'Ajo 35', paivamaara: '26.04.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kaarina', kollienMaara: 2, lisaTiedot: 'Sisältää lääkkeitä', status: 'Aloitettu' },
    { id: 36, nimi: 'Ajo 36', paivamaara: '29.04.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Tornio', kollienMaara: 11, lisaTiedot: 'Polttoaineen lisäys', status: 'Suoritettu' },
    { id: 37, nimi: 'Ajo 37', paivamaara: '02.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Kauhajoki', kollienMaara: 3, lisaTiedot: 'Kuljetus aamulla', status: 'Ei aloitettu' },
    { id: 38, nimi: 'Ajo 38', paivamaara: '05.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Iisalmi', kollienMaara: 22, lisaTiedot: 'Tarkista sääolosuhteet', status: 'Aloitettu' },
    { id: 39, nimi: 'Ajo 39', paivamaara: '08.05.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Pieksämäki', kollienMaara: 20, lisaTiedot: 'Tarkista jarrut', status: 'Suoritettu' },
    { id: 40, nimi: 'Ajo 40', paivamaara: '11.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Siilinjärvi', kollienMaara: 16, lisaTiedot: 'Pitkä matka', status: 'Ei aloitettu' },
    { id: 41, nimi: 'Ajo 41', paivamaara: '14.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Keuruu', kollienMaara: 4, lisaTiedot: 'Tarkkaile sääolosuhteita', status: 'Aloitettu' },
    { id: 42, nimi: 'Ajo 42', paivamaara: '17.05.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Forssa', kollienMaara: 8, lisaTiedot: 'Polttoaine vähissä', status: 'Suoritettu' },
    { id: 43, nimi: 'Ajo 43', paivamaara: '20.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Karkkila', kollienMaara: 1, lisaTiedot: 'Kuljetus klo 16', status: 'Ei aloitettu' },
    { id: 44, nimi: 'Ajo 44', paivamaara: '23.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Pudasjärvi', kollienMaara: 15, lisaTiedot: 'Erikoiskuljetus', status: 'Aloitettu' },
    { id: 45, nimi: 'Ajo 45', paivamaara: '26.05.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Nurmijärvi', kollienMaara: 21, lisaTiedot: 'Tarkista renkaat', status: 'Suoritettu' },
    { id: 46, nimi: 'Ajo 46', paivamaara: '29.05.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Hanko', kollienMaara: 19, lisaTiedot: 'Sisältää ruokatarvikkeita', status: 'Ei aloitettu' },
    { id: 47, nimi: 'Ajo 47', paivamaara: '01.06.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Järvenpää', kollienMaara: 17, lisaTiedot: 'Toimitus klo 9', status: 'Aloitettu' },
    { id: 48, nimi: 'Ajo 48', paivamaara: '04.06.2024', tapahtumanTyyppi: 'Tankkaus', kohde: 'Heinola', kollienMaara: 13, lisaTiedot: 'Tarkista öljytaso', status: 'Suoritettu' },
    { id: 49, nimi: 'Ajo 49', paivamaara: '07.06.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Orivesi', kollienMaara: 23, lisaTiedot: 'Pitkä matka', status: 'Ei aloitettu' },
    { id: 50, nimi: 'Ajo 50', paivamaara: '10.06.2024', tapahtumanTyyppi: 'Ajo', kohde: 'Varkaus', kollienMaara: 14, lisaTiedot: 'Sisältää vaarallista aineistoa', status: 'Aloitettu' },
  ];
  
  export default ajot;